- hosts: master:slaves
  user: vagrant
  tasks:
  - name: Install SELinux dependency
    yum: name=libselinux-python state=present

  - name: Install MariaDB repository
    copy: src=MariaDB.repo dest=/etc/yum.repos.d/

  - name: Install MariaDB Server
    yum: name=MariaDB-server state=latest

  - name: Install python module
    yum: name=MySQL-python state=present
  
  - name: Deploy configuration
    template: src=ms.cnf.j2 dest=/etc/my.cnf.d/ms.cnf

  - name: And start MariaDB
    service: name=mysql state=started

- hosts: master
  user: vagrant
  tasks:

  - name: Create replication user
    mysql_user: name=repl host=% password=lper priv="*.*:REPLICATION SLAVE"

  - name: Create superuser
    mysql_user: name=root host=% password=admin priv=*.*:ALL state=present

  - name: Create maxscale user
    mysql_user: name=maxadmin host="%" password=maxpwd priv="*.*:SELECT,SHOW DATABASES,REPLICATION CLIENT" state=present

- hosts: slaves
  user: vagrant
  tasks:

  - name: Requires mysql start
    service: name=mysql state=started

  - name: Setup replication
    command: /usr/bin/mysql -uroot -e "CHANGE MASTER TO master_host='192.168.56.111', master_user='repl', master_password='lper', master_use_gtid=current_pos"

- include: maxscale.yml

